#!/usr/bin/env zsh

if [[ ! -z $(git status -s) ]]; then
    echo "Please do something ..."
    exit 1
fi

git pull

folders=(
    git
    local
    # nvim
    tmux
    zsh
)

for folder in "${folders[@]}"; do
    echo "Stow process on target dir: ${folder}"
    stow -D $folder
    stow -S $folder
done

