#!/usr/bin/env bash

session=$(find ~ ~/code ~/.nrfconnect-apps/local -mindepth 1 -maxdepth 1 -type d | fzf)
session_name=$(basename "$session" | tr . _)
echo "Session Name: $session_name"
if ! tmux has-session -t "$session_name" 2> /dev/null; then
   echo "Will create new session with name: $session_name"
   tmux new-session -s "$session_name" -c "$session" -d
fi

tmux switch-client -t "$session_name"
